### PR TITLE
Add support for hostname binding for http/https gateway

### PR DESCRIPTION
**Pull request by XVincentX**
Continuing from #845

@bploetz I'd appreciate if you could actually try this branch on your system to confirm the feature is working correctly.

### CODE REVIEW

**Comment by bploetz** [comment]
@XVincentX Sorry, a little confused by the moving target here. So we've moved the work to this PR #846, and it looks like you still need me to write the tests, correct? Happy to do so, but just an FYI with the holiday here in the US, I likely won't get to this until this weekend. Stay tuned.....

**Comment by XVincentX** [comment]
@bploetz Do not worry — enjoy your vacation. I think I'll move this over the finish line in meantime then :)

**Comment by XVincentX** [comment]
@bploetz Do not worry, it's perfectly fine. Is there any way you could test this on your servers and let me know if your use case is fulfilled?

**Comment by bploetz** [comment]
@XVincentX Sure thing. Stay tuned.....

**Comment by bploetz** [comment]
@XVincentX the `http` server seems to work fine.

```
> grep "express-gateway" package-lock.json 
    "express-gateway": {
      "version": "github:ExpressGateway/express-gateway#15bd49cb8d6955b801823a4aaf9291a343219397",
      "from": "github:ExpressGateway/express-gateway#feature/gateway_listen_host",
```

gateway.config.yml:
```
http:
  port: 8080
  hostname: 0.0.0.0

https:
  port: 8443
  hostname: 0.0.0.0

admin:
  port: 9876
  hostname: 0.0.0.0
```

```
api-gateway_1  | 2018-11-26T15:54:47.650Z [EG:gateway] info: gateway http server listening on 0.0.0.0:8080
```

And I can communicate with the gateway `http` server via the configured port.

However, I can't seem to connect to the `https` gateway server. It looks like the changes you made should have applied to both the `http` and the `https` gateway servers, but I don't see the `https` gateway server's info logged when the gateway starts up like the `http` server does. Output from docker-compose up:

```
api-gateway_1  | > api-gateway@1.0.0 start /opt/api-gateway
api-gateway_1  | > node server.js
api-gateway_1  | 
api-gateway_1  | 2018-11-26T15:54:46.728Z [EG:gateway] warn: rewrite plugin hasn't provided a schema. Validation for this plugin will be skipped.
api-gateway_1  | 2018-11-26T15:54:47.019Z [EG:plugins] info: Loaded plugin rewrite from package express-gateway-plugin-rewrite
api-gateway_1  | 2018-11-26T15:54:47.650Z [EG:gateway] info: gateway http server listening on 0.0.0.0:8080
api-gateway_1  | 2018-11-26T15:54:47.651Z [EG:admin] info: admin http server listening on 0.0.0.0:9876
```

And when I try to talk to the https gateway server I get `curl: (35) Server aborted the SSL handshake`. When I try to telnet to the 8443 port on localhost (container is running in bridge mode) I get:

```
telnet localhost 8443
Trying ::1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

Whereas I can telnet to the http port 8080 just fine.

Thoughts?

**Comment by XVincentX** [comment]
@bploetz This is because you haven't provided the `tls` object — it's mandatory for https servers.

https://www.express-gateway.io/docs/configuration/gateway.config.yml/https/

I'm going to add a warn so you do not go in trouble again next time. Good point.

**Comment by bploetz** [comment]
Nice! Any idea what version this will be in @XVincentX ?

**Comment by XVincentX** [comment]
It should be in 1.14 — but I can’t give you an ETA for release. We still have some chores/errands to review and merge before putting it live. Hopefully soon :)

**Comment by bploetz** [comment]
@XVincentX cool thanks

**Comment by XVincentX** [comment]
@bploetz This is now in 1.14.0

**Comment by bploetz** [comment]
Awesome! Thanks @XVincentX !

**Comment by altsang** [comment]
Thanks for your patience on this Brian, sorry it took so long


On December 21, 2018 at 10:15:09 AM, Brian Ploetz (notifications@github.com)
wrote:

Awesome! Thanks @XVincentX <https://github.com/XVincentX> !

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ExpressGateway/express-gateway/pull/846#issuecomment-449460344>,
or mute the thread

**Comment by bploetz** [comment]
No worries @altsang. Had my package.json file pointed at the sha in the mean time. :) Thanks again guys!

**Comment by altsang** [comment]
HA! I *knew* it :P


On December 21, 2018 at 10:17:04 AM, Brian Ploetz (notifications@github.com)
wrote:

No worries @altsang <https://github.com/altsang>. Had my package.json file
pointed at the sha in the mean time. :) Thanks again guys!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ExpressGateway/express-gateway/pull/846#issuecomment-449460787>,
or mute the thread

**Pull request merged**
