### PR TITLE
changing server start method

### PR DESCRIPTION
**Pull request by taewdy**
Hi, @XVincentX 
Creating another PR due to error from the test I didn't touch.
Anyway, fixed code based on your suggestion.
and I'm also happy if you modify any shortcomings you see with this PR.
Thanks

### CODE REVIEW

**Comment by taewdy** [comment]
I'm getting errors again from the test not related to my modification :(

**Comment by XVincentX** [comment]
@taewdy Would it be possible for you to enable edit from maintainers so I can have a look and make the necessary changes to the PR so tests pass?

**Comment by taewdy** [comment]
No worries, thanks for the follow up. Just invited you as a collaborator on the forked repositories. I guess this is it? If not please let me know. Thanks!

**Comment by XVincentX** [comment]
Hmm not really. The idea would be you to click this button on the pull request.

image

**Comment by taewdy** [comment]
If that's the case, it was checked even before I added you as a collaborator. The help says you need write access to the forked master branch, which I just did by adding you as a collaborator. Could you try again? If it doesn't work, maybe I need to do something else.


screenshot from 2018-05-09 20-59-20

**Comment by XVincentX** [comment]
Oh ok thanks — let me have a look into.

**Comment by XVincentX** [comment]
@taewdy This seems to be a little bit more difficult than expected. Unfortunately some parts of the test suite are really weird and not so easy to improve.

The ideal, to close this weird issue, would be to completely remove the `startServer` and `spawn` function and use the one provided already in `gateway.helper` — modifying the function if required to accommodate this particular test scenario.

This is not an easy task, and I'll probably tackle it down in the near term future. If you still want to work on this, you're more than welcomed to do so, but it's not going to be easy. Just let me know your intentions, and I'll react accordingly.

Thanks a lot again for your time here, it's really appreciated.

**Comment by taewdy** [comment]
Hi @XVincentX,
thanks for taking time to examine the PR, I also noticed while I do the PR that it's kinda in the CI process, didn't realize it when I was testing locally. The necessity for me was I was only testing that module independetly, so I needed it to work accordingly. But it's alrealy in the CI and being taken care of, so I'm happy the PR can be dropped. Thanks again for going through PR. and again great job on the Express Gateway. I really appreciate your works.
Thanks

**Pull request closed without merging**
