### PR TITLE
Update ioredis-mock to latest version

### LINKED ISSUE #564: Use transformers implementation in ioredis-mock and remove workarounds in code
Due to original version of ioredis-mock not containing ioredis argument\reply transformers some workarounds were taken to make the code work. 

The problem is now solved and those workarounds can be safely removed

### PR DESCRIPTION
**Pull request by XVincentX**
Connect #564 
Connect #537 
Closes #564

Pending new `ioredis-mock` release

### CODE REVIEW

**Comment by DrMegavolt** [comment]
check out  `return db.hmset(appHashKey(id), 'isActive', 'true', 'updatedAt', String(new Date()));`
style usage, can it be reverted to `{isActive:"true",  updatedAt : String(new Date())) } ` style ?

**Comment by XVincentX** [comment]
Whoa! Good catch! Although it seems like it was an array, not an object: 
https://github.com/ExpressGateway/express-gateway/pull/501/files#diff-a84828d7e5fb2b16bc57843ffd196ee3L110

I'll try once the library is up

**Comment by XVincentX** [comment]
@DrMegavolt It seems to be ok now

**Comment by DrMegavolt** [comment]
`  return db.hset(buildIdKey(type, id), 'isActive', 'false', 'updatedAt', String(new Date()));`
It seems to be a bug. don't know how it was introduced. 

HSET will set only first field
can you change that to hmset and update arguments to object format ?

**Comment by XVincentX** [comment]
@DrMegavolt 
I was trying to figure out why the tests were passing correctly and…

> As of now, Oct 2017, HSET in the current redis version (4.0.2) can also set multiple key-value pairs.

It seems like these commands now behave in the same way.

**Comment by DrMegavolt** [comment]
hm, ok
* HSET is now variadic, and HMSET is considered deprecated (but will be supported for years to come). Please use HSET in new code.
https://raw.githubusercontent.com/antirez/redis/4.0/00-RELEASENOTES

so we can skip it for now.

**Comment by XVincentX** [comment]
I'll create a new issue with veeeery low priority.

**Comment by DrMegavolt** [comment]
I'm not sure we should fix it at all. 
I don't have any credible info about version in flights. 
Consider this https://duo.com/blog/over-18000-redis-instances-targeted-by-fake-ransomware
so it was a lot of redis servers below current at that time 3.2 

and since 4.0 has some breaking changes I guess 3.x is still in wide usage

**Comment by XVincentX** [comment]
That makes sense. Let's talk again about it in…3 years :trollface:

**Pull request merged**
