### PR TITLE
Make the gateway tests run on Node 9 correctly

### PR DESCRIPTION
**Pull request by DrMegavolt**

### CODE REVIEW

**Comment by XVincentX** [comment]
Connect #586 
Closes #586

**Comment by XVincentX** [comment]
The reason why tests are failing is because of the way we spin up gateway instances for e2e tests.
I do not properly remember the thing, but I'll investigate again and fix that hopefully.

**Comment by XVincentX** [comment]
This PR will ensure Node 9 compatibility with the following things:

* Node is slowly moving to [static error codes](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V9.md#9.0.0), so the string errors will slowly disappear: a4a85cc

* The E2E tests were initiating a whole new gateway instance from scratch, reinstalling all the dependencies, *BUT* at the end the new installed gateway is not used at all. It was probably just a way to initialize a config directory with the required data. This was cause of flakyness and errors in node 9 ce5da59 and 197a0fa

* Removed a stale Docker file and modified the current one so that's relying on `node8-alpine` instead to the latest `alpine`

**Comment by XVincentX** [comment]
@DrMegavolt I can't assign you as a reviewer since you opened the PR.

**Comment by DrMegavolt** [comment]
@XVincentX LGTM

**Pull request merged**
