### PR TITLE
Replace policy from class to functions — Connect LunchBadger/general#487 Closes Connect LunchBadger/general#487

### PR DESCRIPTION
**Pull request by XVincentX**
This PR is a small code refactor to transform the current policy to be a singleton class to an object which exports 3 functions.

As we're using almost functions everywhere and not classes, I think unifying the things here and there is beneficial to lower the contribution barrier.

### CODE REVIEW

**Comment by DrMegavolt** [comment]
There are no advanced concepts in current version. Class is standard ES6 feature, no difference to have instance of the class or export functions.

**Comment by XVincentX** [comment]
I agree that this is not bringing any new feature or improvement. My aim was not that one indeed. My aim was to make the code less complex — which I feel the class construct brings.

When you see a class you mentally start to think to an internal state, multiple instances, maybe inheritance — all things that in this case aren't happening.

Reducing the cognitive load is important to onboard new people on the project and lower the contribution barrier.

This change, _alone_, won't change the things. Complexity is something you accumulate with small steps and dismantle with small steps. This — I think, is one of these.

@kevinswiber What's your thought?

**Comment by kevinswiber** [comment]
I understand this in terms of consistency less than I do in terms of complexity.  

What I like about the class approach is that the `policies` array is mutable, which might be handy for test scenarios.  (I'm currently working on plugin testing, so maybe that's why this is top of mind.)  With the approach in this PR, that `policies` list is inaccessible.

I agree with closing this for now.

**Comment by XVincentX** [comment]
@kevinswiber The `policies` array is exposed [here](https://github.com/ExpressGateway/express-gateway/pull/824/files#diff-6dd40befa5e020684f04fdd9e88783b9R63) — or am I missing something?

**Comment by kevinswiber** [comment]
@XVincentX Ah, nope.  I missed something!  In that case, I'd be in favor of this PR for consistency reasons.  I don't think the class adds any complexity, but if it's one of few (if any) classes in the codebase, that's a bit weird.

**Comment by kevinswiber** [comment]
@DrMegavolt Can you agree to this PR for consistency reasons (as opposed to complexity)?

**Comment by DrMegavolt** [comment]
ok

**Pull request closed without merging**
