### PR TITLE
fix[UI]: improve consent page

### LINKED ISSUE #739: Consent page improvements: minimal style + scope show
The consent page we're offering right now is really spartane.

Let's add some minimal style and, more importantly, let's clearly show to the user the scopes that the current application is requesting.

### PR DESCRIPTION
**Pull request by ravikp7**
fixes #739

### CODE REVIEW

**Comment by XVincentX** [comment]
Hey @ravikp7 — good start. There are couple of additional things I'd like to see here though

1. The scope consent page is not styled. It'd be great to style this as well so that the flow is consistent
2. It'd be great to be consistent with our [website styling](https://express-gateway.io), in particular the font style and the colours. Also, I wouldn't mind having a logo somewhere up!


I know this can be annoying — just let me know in case you're not up for it and I will take it over the finish line.

**Comment by ravikp7** [comment]
@XVincentX yeah, the scope consent page is still pending, will take care of that as well as the styling and logo

**Comment by ravikp7** [comment]
- Logo, consistent font and color

Screenshot from 2019-04-18 00-53-23

**Comment by ravikp7** [comment]
- Show requesting scopes

Screenshot from 2019-04-22 19-11-35

**Comment by XVincentX** [comment]
Sweet! I'll review and merge!

**Pull request merged**
