### PR TITLE
Update README file with how to run tests section

### PR DESCRIPTION
**Pull request by Saganus**
Hello!

I'd love to contribute code to the project, but before doing that I would like to have a working dev environment. Being able to run the tests seemed like a good place to start, but I had several missing dependencies.

So I installed them one by one until I didn't get any more errors and this is the list of missing packages I had to install. 

I figured that to make it easier for others to start contributing I'd update the readme with the list. 

The only thing I'm not sure is if I'm getting the correct error results.

I'm basically getting about 3k errors regarding expected indentations and a couple of "warning  Unexpected console statement" which seem to be harmless so, can I assume the tests are running successfully? or am I missing something?

Thanks!

### CODE REVIEW

**Comment by kevinswiber** [comment]
Hey, @Saganus!

Thanks for the PR.

This should work out of the box:
1. `git clone https://github.com/ExpressGateway/express-gateway.git`
2. `cd express-gateway && npm install`
3. `npm run test-all`

What version of Node are you running?  What version of NPM?  What operating system are you using?

**Comment by Saganus** [comment]
You are correct.

I did a fresh installation and it worked fine. 

Uhmm... I guess I must have a corrupt install or something. Sorry about that.

How can I cancel the pull request?

Thanks!

**Comment by kevinswiber** [comment]
Hey, no worries!  Any reported issue is great, even better with a Pull Request!

You can always close a Pull Request you open.  Instructions here: https://help.github.com/articles/closing-a-pull-request/

**Comment by Saganus** [comment]
Definitely off my game today... Can't believe I didn't see the big button below... 

Thanks for the patience.

**Pull request closed without merging**
