### PR TITLE
Encode queryparams in admin helpers

### LINKED ISSUE #572: REST helpers should properly encode query parameters
All the admin helpers (used by the CLI) are concatenating url parameters as plain [strings](https://github.com/ExpressGateway/express-gateway/blob/master/admin/users.js#L18)

This means that if I put an user with some URL-unsafe characters, I'll receive a not found message (although the user probably exists) or even an error.

This might be a good occasion to also DRY the admin client as well. A lot of copy paste is happening there.

### PR DESCRIPTION
**Pull request by iwko**
The following PR will provide url encoding in admin helpers

Closes #572

### CODE REVIEW

**Comment by XVincentX** [comment]
Thanks a lot for this. I'm currently in USA — I'll review this work once back in Madrid. Thanks!

**Comment by DrMegavolt** [comment]
Thanks @iwko!

**Comment by XVincentX** [comment]
Ok with this. Maybe next time let's make sure to add tests at least.

**Comment by iwko** [comment]
@XVincentX  

Okay!

**Pull request merged**
